function turbidityvalues2020 = import_turbidity(filename, dataLines)
%IMPORTFILE Import data from a text file
%  TURBIDITYVALUES2020 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  TURBIDITYVALUES2020 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  turbidityvalues2020 = importfile("D:\TURNER\DISCHARGE\data\turbidity_values2020.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 27-Jun-2022 12:33:14

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["systemindex", "prop", "geo"];
opts.VariableTypes = ["double", "double", "categorical"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "geo", "EmptyFieldRule", "auto");

% Import the data
turbidityvalues2020 = readtable(filename, opts);

end