function acquisitiondatesb11sentinel2 = importfile_S2dates(filename, dataLines)
%IMPORTFILE Import data from a text file
%  ACQUISITIONDATESB11SENTINEL2 = IMPORTFILE(FILENAME) reads data from
%  text file FILENAME for the default selection.  Returns the data as a
%  table.
%
%  ACQUISITIONDATESB11SENTINEL2 = IMPORTFILE(FILE, DATALINES) reads data
%  for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  acquisitiondatesb11sentinel2 = importfile("C:\Users\Yoram\OneDrive - University of Idaho\Desktop\PhD pos\TURNER\seismic\GHT_matlab\turbidityvalues\acquisition_dates_b11_sentinel2.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 28-Jun-2022 13:39:40

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "_";

% Specify column names and types
opts.VariableNames = ["systemindexpropgeo", "date", "VarName3"];
opts.VariableTypes = ["string", "datetime", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "systemindexpropgeo", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "systemindexpropgeo", "EmptyFieldRule", "auto");
opts = setvaropts(opts, "date", "InputFormat", "yyyyMMdd'T'HHmmss");
opts = setvaropts(opts, "VarName3", "TrimNonNumeric", true);
opts = setvaropts(opts, "VarName3", "ThousandsSeparator", ",");

% Import the data
acquisitiondatesb11sentinel2 = readtable(filename, opts);

end